import React, { useState, useEffect } from 'react';
import { collection, query, orderBy, limit, getDocs, doc, deleteDoc } from 'firebase/firestore';
import { db } from '../src/firebase';
import { Download, Compass, ArrowLeft, Trash2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { User } from 'firebase/auth';

export const DiscoverSection: React.FC<{ onBack?: () => void, currentUser?: User | null }> = ({ onBack, currentUser }) => {
  const [gallery, setGallery] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDeleting, setIsDeleting] = useState<string | null>(null);

  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);

  const fetchGallery = async () => {
    setIsLoading(true);
    try {
      const q = query(collection(db, 'gallery'), orderBy('publishedAt', 'desc'), limit(30));
      const snapshot = await getDocs(q);
      const docs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setGallery(docs);
    } catch (err) {
      console.error("Error fetching gallery:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchGallery();
  }, []);

  const handleDelete = async (id: string) => {
    if (!currentUser) return;
    setIsDeleting(id);
    try {
      await deleteDoc(doc(db, 'gallery', id));
      setGallery(prev => prev.filter(item => item.id !== id));
      setConfirmDeleteId(null);
    } catch (err) {
      console.error("Error deleting gallery item", err);
      // alert("Failed to delete stencil. Make sure you have permission.");
    } finally {
      setIsDeleting(null);
    }
  };

  if (isLoading && gallery.length === 0) {
    return (
      <div className="w-full h-64 flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-orange-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 md:px-8 py-12 flex flex-col items-center">
      {onBack && (
        <button 
          onClick={onBack}
          className="self-start mb-8 flex items-center gap-2 text-zinc-400 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
      )}
      <div className="text-center mb-12 space-y-4">
         <div className="inline-flex items-center justify-center p-3 bg-orange-600/10 rounded-2xl mb-2">
            <Compass className="w-8 h-8 text-orange-500" />
         </div>
         <h2 className="text-3xl md:text-5xl font-bold tracking-tight text-white">Inspiration Gallery</h2>
         <p className="text-zinc-500 max-w-xl mx-auto">
           Discover incredible stencils generated by other tattoo artists.
         </p>
      </div>

      {gallery.length === 0 ? (
        <div className="text-zinc-600 mt-12">No public stencils yet. Generate and share one to be the first!</div>
      ) : (
        <div className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 gap-6 w-full space-y-6 pb-24">
          {gallery.map((item, index) => (
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              key={item.id} 
              className="break-inside-avoid bg-zinc-900 border border-white/5 rounded-3xl overflow-hidden group relative"
            >
              <img src={item.stencilImage} alt="Stencil" className="w-full h-auto bg-white/5" />
              <div className="absolute inset-x-0 bottom-0 p-4 bg-gradient-to-t from-black/80 via-black/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity">
                <div className="flex justify-between items-end">
                  <span className="text-xs font-bold text-orange-500 bg-orange-500/20 px-2 py-1 rounded-full">{item.styleName || 'Pro Stencil'}</span>
                  <div className="flex gap-2">
                    {currentUser?.uid === item.uid && (
                      <>
                        {confirmDeleteId === item.id ? (
                          <div className="flex items-center gap-1 bg-red-900/80 backdrop-blur-md rounded-full px-2 py-1">
                            <span className="text-white text-xs font-bold px-1">Delete?</span>
                            <button
                              onClick={(e) => { e.stopPropagation(); handleDelete(item.id); }}
                              disabled={isDeleting === item.id}
                              className="p-1.5 bg-red-500 hover:bg-red-600 rounded-full text-white transition-colors"
                            >
                              <Trash2 className="w-3 h-3" />
                            </button>
                            <button
                              onClick={(e) => { e.stopPropagation(); setConfirmDeleteId(null); }}
                              className="p-1.5 bg-zinc-700 hover:bg-zinc-600 rounded-full text-white transition-colors"
                            >
                              <ArrowLeft className="w-3 h-3" />
                            </button>
                          </div>
                        ) : (
                          <button 
                            onClick={(e) => {
                              e.stopPropagation();
                              setConfirmDeleteId(item.id);
                            }}
                            className="p-2 bg-red-500/20 hover:bg-red-500/40 rounded-full text-red-500 backdrop-blur-md transition-colors"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        )}
                      </>
                    )}
                    <button 
                      onClick={() => {
                          const link = document.createElement('a');
                          link.href = item.stencilImage;
                          link.download = `prostencils-discover-${item.id}.png`;
                          link.click();
                      }}
                      className="p-2 bg-white/20 hover:bg-white/40 rounded-full text-white backdrop-blur-md transition-colors"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
};
